### ISSUE TITLE
Question about the equation in Paper

### ISSUE THREAD

**Issue by xichaoqiang** [Xindingfang/grtm#1]
Hello Dr Fang,

Thanks for sharing this package.

When I read your paper <Generation of 6-C Synthetic Seismograms in Stratified Vertically-Transversely-Isotropic Media Using a Generalized Reflection and Transmission Coefficient Method>.

I found the eq 2-1-11 and eq 2-1-13 are differ from eq 7 in published paper (Ji et al,. 2020, Geophysics ).

< Calculation method and characteristic analysis of dispersion curves of Rayleigh channel waves in transversely isotropic media>

![图片](https://user-images.githubusercontent.com/30900789/107967618-4ecbb180-6fe8-11eb-85e7-a05beb815f7f.png)

And eq B2 in  (Gofer, E. , & Bachrach, R. . 2019 ,Geophysical Prospecting) 

<Anisotropic azimuthal surface-wave inversion for a vertically fractured and transverse isotropy medium: Theory and examples from a controlled field experiment>

![图片](https://user-images.githubusercontent.com/30900789/107968037-d31e3480-6fe8-11eb-9633-276e08cbcd9a.png)

Is there any problem?

Best regards,
Xi

**Comment by Xindingfang** [comment]
> Hello Dr Fang,
> 
> Thanks for sharing this package.
> 
> When I read your paper <Generation of 6-C Synthetic Seismograms in Stratified Vertically-Transversely-Isotropic Media Using a Generalized Reflection and Transmission Coefficient Method>.
> 
> I found the eq 2-1-11 and eq 2-1-13 are differ from eq 7 in published paper (Ji et al,. 2020, Geophysics ).
> 
> < Calculation method and characteristic analysis of dispersion curves of Rayleigh channel waves in transversely isotropic media>
> 
> ![图片](https://user-images.githubusercontent.com/30900789/107967618-4ecbb180-6fe8-11eb-85e7-a05beb815f7f.png)
> 
> And eq B2 in (Gofer, E. , & Bachrach, R. . 2019 ,Geophysical Prospecting)
> 
> ![图片](https://user-images.githubusercontent.com/30900789/107968037-d31e3480-6fe8-11eb-9633-276e08cbcd9a.png)
> 
> Is there any problem?
> 
> Best regards,
> Xi

Hello Xi,

Eq. (7) in (Ji et al, 2020, Geophysics ) is actually identical to Eq. (2-2-13) in our GJI paper. In a VTI medium, C44 is equal to C55. A VTI medium becomes an HTI medium when its symmetric axis changes from vertical to horizontal. So C66 of an HTI medium is equivalent to C44 or C55 in the corresponding VTI medium.

Regarding Eq B2 in Gofer's GP paper, I suspect that there is something wrong with the 4th-row 2nd-column entry.

Hope my answer can be useful.

Best,
Xinding

**Comment by xichaoqiang** [comment]
Hello Dr Fang,

Thanks for your kindly reply. Your reply helps me alot.

This package is  well written and very detailed. 

Is there any phase and group velocity dipsersion curve forwarding function in the package?

And how can I get the kernel function of Green's function?

Best regards,
Xi

**Comment by Xindingfang** [comment]
Hi Xi, there is no standalone subroutine for dispersion calculation in this package.

**Comment by Xindingfang** [comment]
Hi Xi, there is no standalone subroutine for dispersion calculation in this package.

**Comment by xichaoqiang** [comment]
Dr Fang.Thanks for your reply.
